site_name: USTC CPCT 2025 课程主页
repo_name: cpct2025/cpct2025.github.io
repo_url: https://github.com/cpct2025/cpct2025.github.io
theme:
  name: "material"
  language: "zh"
  font: false
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换至深色模式
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: 切换至浅色模式
  icon:
    repo: octicons/mark-github-16
  features:
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.top
    - navigation.tracking

plugin:
  - search
  - offline
  - privacy

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - markdown.extensions.def_list
  - toc:
      permalink: true

nav:
  - 首页: README.md
  - lab0:
      - Markdown 教程: lab0/markdown.md
      - Git 教程: lab0/git.md
      - IDE 安装教程: lab0/ide_installation.md
  - Hint: hint/hint.md
  - FAQ: faq/FAQ.md
  - 勘误: errata/errata.md

extra_javascript:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - mkdocs/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
extra_css:
  # [数学公式支持]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
