name: Deploy to GH Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 安装 uv
        uses: astral-sh/setup-uv@v5

      - name: "安装 Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - run: uv lock
      - name: 安装项目
        run: uv sync --locked --all-extras --dev

      - run: uv run mkdocs build
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deploy-pages
